-- dropping additional database objects
drop view if exists view_with_rules;
drop table if exists view_with_rules_t1;
drop table if exists view_with_rules_t2;
drop foreign data wrapper if exists dummy cascade;
drop server if exists srv1 cascade;
drop server if exists srv2 cascade;
drop type if exists my_complex;
drop type if exists person_name;
drop type if exists punkt cascade;
drop type if exists kleinkreis;
drop type if exists weg;
drop type if exists sex;
drop type if exists mood;
drop type if exists literas;
drop event trigger if exists abort_ddl cascade;
drop function if exists abort_any_command() cascade;
drop type if exists employee_type cascade;
drop table if exists employees;
drop table if exists rich_table;
drop table if exists like_table2;
drop table if exists table_a cascade;
drop table if exists table_b cascade;
drop table if exists table_c cascade;
drop table if exists table_d cascade;
drop table if exists table_with_column_of_many_types cascade;
drop table if exists inventory cascade;
drop table if exists inventory cascade;
drop table if exists p1 cascade;
drop table if exists p2 cascade;
drop table if exists p3 cascade;
drop table if exists p4 cascade;
drop table if exists p11 cascade;
drop function if exists add_suffix_if_not_exists() cascade;
drop operator if exists @@+(varchar, varchar);
drop function if exists near(int, int) cascade;
drop operator if exists !!!(varchar, none);
drop operator if exists <+>(none, integer);
drop function if exists to_string_with_plus(int);
drop function if exists quote_it(varchar);
drop materialized view if exists matv;
drop table if exists taba;
drop table if exists my_table;
drop table if exists my_insane_table;
drop function if exists param_def_516_1(int, varchar);
drop function if exists param_def_516_1(int, varchar);
drop function if exists function_044();
drop foreign table if exists "my foreign table";
drop extension if exists hstore cascade;
drop domain if exists person_dob;
drop table if exists master cascade;
drop table if exists refer;
drop function if exists _group_concat(text, text) cascade;
drop function if exists _group_concat(text) cascade;
drop function if exists mf(text, text) cascade;
drop function if exists mvf(text, text) cascade;
drop function if exists mff(text, text) cascade;
drop function if exists final(text, text, text) cascade;
drop function if exists final(text, text) cascade;
drop aggregate if exists group_concat2(text) cascade;
drop function if exists add_suffix_if_not_exists(varchar, varchar);
drop function if exists add_suffix_if_not_exists(varchar);
