drop table Simple_Table_with_Checks cascade constraints;
drop table divisions;
drop table STREET;
drop cluster STREETS;
drop materialized view my_basic_materialized_view;
drop table my_basic_table;
drop package SIMPLE_PACK;
drop package SIMPLE_PACK2;
drop sequence sequence_with_many_parameters;
drop synonym JUST_TABLE;
drop synonym JUST_VIEW;
drop table SIMPLE_SIMPLE_TABLE;
drop view SIMPLE_SIMPLE_VIEW;
drop table Ephemera_1;
drop table Ephemera_2;
drop trigger T1_kind_tr;
drop table T1;
drop type data_type_alter;
drop type words;
drop type textdoc_tab;
drop type textdoc_typ;
drop view View_From_Dual;
